version: "3"
services:
  mysql-server:
    container_name: "music-meta-service-mysql"
    image: "mysql/mysql-server:5.7"
    ports:
      - "13333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "AdlXFlJIgDZU2AEh1drh"
      MYSQL_DATABASE: "music_meta_service"
      MYSQL_USER: "mms_user"
      MYSQL_PASSWORD: "rm4rM16UEGxBW4nU2Gpo"
    volumes:
      - "./support/local-mysql-init.sql:/docker-entrypoint-initdb.d/init.sql"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
